#!/bin/bash
set -e
export CI=true

# Add remote if missing.
git remote add heroku git@heroku.com:deployer.git 2>/dev/null

echo "Running unit tests."
bundle exec rake spec:unit

echo
echo "Preparing database."
bundle exec rake db:migrate db:test:prepare

echo
echo "Running integrated tests with the memory store."
bundle exec rake spec

echo
echo "Running integrated tests with the postgres store."
bundle exec rake spec DB=true
