#!/bin/bash
set -e
export CI=true

echo "Running unit tests."
bundle exec rake spec:unit

echo
echo "Preparing database."
RAILS_ENV=test bundle exec rake db:schema:load

echo
echo "Running integrated tests."
bundle exec rake spec
