#!/usr/bin/env ruby
#
# Command to run the specs the correct way when triggered from the turbux vim plugin.

rails_spec = ARGV.first.start_with?("spec/") || ARGV.first.include?('/spec/')

if rails_spec
  command = "rspec"
else
  # Don't load bundler for non-rails unit tests
  command = "RUBYOPT='' rspec --color --tty"
end

command += " #{ARGV.first}"
exit(1) unless system(command)
